export type httpStatusCode =
  | "SUCCESS"
  | "BAD_REQUEST"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "CONFLICT"
  | "VALIDATION_ERROR"
  | "SERVICE_UNAVAILABLE"
  | "GATEWAY_TIMEOUT"
  | "TOO_MANY_REQUESTS"
  | "INTERNAL_SERVER_ERROR";
